#include <stddef.h>
#include <string.h>
#include <stdlib.h>

#include "parse/token.h"

const char *token_type_str[NUM_TOKENS] = {
    "<EOF>",
    "(",
    ")",
    "<numeral>",
    "<decimal>",
    "<binary>",
    "<hex>",
    "<string>",
    "par",
    "NUMERAL",
    "DECIMAL",
    "STRING",
    "_",
    "!",
    "#",
    "as",
    "let",
    "exists",
    "forall",
    "define-system",
    "check-system",
    "declare-sort",
    "declare-enum-sort",
    "declare-const",
    "declare-fun",
    "define-sort",
    "define-const",
    "define-fun",
    "exit",
    "set-logic",
    "echo",
    "reset",
    "assert",
    ":input",
    ":output",
    ":local",
    ":init",
    ":trans",
    ":inv",
    ":subsys",
    ":assumption",
    ":reachable",
    ":fairness",
    ":current",
    ":query",
    ":queries",
    "<unknown-keyword>",
    "<symbol>",
    "<error-const>",
    "<error-num-zero>",
    "<error-quote-eof>",
    "<error-quote-char>",
    "<error-string-eof>",
    "<error-string-char>",
    "<error-symbol>",
    "<error-keyword>",
    "<error>"
};
